Repository w3c/vc-data-model, pull requests merged in 2019-03, with the labels that each got.

#454 tweak i18n considerations
  CR/2019-03-26/index.html
  index.html
Labels: i18n-comment

#460 Zkp section addition
  index.html
Labels: Clarification

#461 fix revocation by issuer #456
  index.html
Labels: editorial

#469 Exemplify language tagging
  contexts/credentials/examples/v1
  index.html
Labels: i18n-comment
