Repository w3c/vc-data-model, pull requests merged in 2022-02, with the labels that each got.

#866 address clarification that the URI can be used to retrieve data
  index.html
Labels: Editorial, Errata, v1.1 (editorial), merge after 14 days

#868 Updating References in the note on transitive trust
  index.html
Labels: Errata, v1.1 (editorial), merge after 14 days

#847 add section to differentiate between contexts and credential Schemas
  index.html
Labels: v1.1 (editorial), merge after 14 days

#872 Update example 20
  index.html
Labels: v1.1 (editorial)
