Repository w3c/vc-data-model, pull requests merged in 2023-12, with the labels that each got.

#1361 Remove unnecessary vocab comments in vocabulary.yml
  vocab/credentials/v2/vocabulary.yml
Labels: editorial, post-CR

#1338 Add verification algorithm to specification.
  index.html
Labels: before-CR

#1380 Add requirements for securing mechanism specifications.
  index.html
Labels: before-CR

#1381 Remove document conformance checking algorithm section
  index.html
Labels: before-CR

#1382 Remove mentions to media type parameters
  index.html
Labels: before-CR

#1383 Add normative references to INFRA in algorithms
  index.html
Labels: before-CR

#1387 Updating the vocab diagram
  vocab/credentials/v2/template.html
  vocab/credentials/v2/vocabulary.drawio
  vocab/credentials/v2/vocabulary.svg
  vocab/credentials/v2/vocabulary.yml
Labels: before-CR

#1390 Clarify that non-objects aren't allowed as VC graphs.
  index.html
Labels: before-CR

#1395 Add missing digestMultibase value in base context.
  contexts/credentials/v2
Labels: post-CR

#1389 Clarify that "proof" is an extension point
  index.html
Labels: before-CR

#1393 Clarify how issuer validation occurs.
  index.html
Labels: before-CR

#1394 Use new Securing Mechanism Verify Proof interface
  index.html
Labels: before-CR
