Repository w3c/vc-data-model, pull requests merged in 2024-02, with the labels that each got.

#1422 Unnecessary "`" signs in i18n examples
  index.html
Labels: editorial, post-CR

#1426 Update echidna.yml for CR
  .github/workflows/echidna.yml
Labels: editorial

#1413 Add intro to Credential Type-Specific Processing.
  index.html
Labels: editorial

#1420 Updated section on semantic interoperability (issues #1217 and #1210)
  index.html
Labels: post-CR, normative

#1423 Update typo
  index.html
Labels: editorial, post-CR

#1425 Update the French examples
  index.html
Labels: editorial, post-CR

#1428 Context formatting nits.
  contexts/credentials/v2
Labels: editorial

#1429 add link to Use Cases doc, remove use cases section.
  index.html
Labels: editorial

#1430 Add `encodedList` type in context.
  contexts/credentials/v2
Labels: editorial

#1435 Update refresh service example to use example from CCG spec.
  index.html
Labels: normative

#1436 Update vocabulary and template files
  vocab/credentials/v2/template.html
  vocab/credentials/v2/vocabulary.yml
Labels: editorial

#1443 Proper rendering of sha-512 values
  index.html
Labels: editorial
